// Generated by gencpp from file planification/Occupancy.msg
// DO NOT EDIT!


#ifndef PLANIFICATION_MESSAGE_OCCUPANCY_H
#define PLANIFICATION_MESSAGE_OCCUPANCY_H

#include <ros/service_traits.h>


#include <planification/OccupancyRequest.h>
#include <planification/OccupancyResponse.h>


namespace planification
{

struct Occupancy
{

typedef OccupancyRequest Request;
typedef OccupancyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Occupancy
} // namespace planification


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planification::Occupancy > {
  static const char* value()
  {
    return "749473d2fd96a6f0862babbe2b5b4470";
  }

  static const char* value(const ::planification::Occupancy&) { return value(); }
};

template<>
struct DataType< ::planification::Occupancy > {
  static const char* value()
  {
    return "planification/Occupancy";
  }

  static const char* value(const ::planification::Occupancy&) { return value(); }
};


// service_traits::MD5Sum< ::planification::OccupancyRequest> should match 
// service_traits::MD5Sum< ::planification::Occupancy > 
template<>
struct MD5Sum< ::planification::OccupancyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planification::Occupancy >::value();
  }
  static const char* value(const ::planification::OccupancyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planification::OccupancyRequest> should match 
// service_traits::DataType< ::planification::Occupancy > 
template<>
struct DataType< ::planification::OccupancyRequest>
{
  static const char* value()
  {
    return DataType< ::planification::Occupancy >::value();
  }
  static const char* value(const ::planification::OccupancyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planification::OccupancyResponse> should match 
// service_traits::MD5Sum< ::planification::Occupancy > 
template<>
struct MD5Sum< ::planification::OccupancyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planification::Occupancy >::value();
  }
  static const char* value(const ::planification::OccupancyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planification::OccupancyResponse> should match 
// service_traits::DataType< ::planification::Occupancy > 
template<>
struct DataType< ::planification::OccupancyResponse>
{
  static const char* value()
  {
    return DataType< ::planification::Occupancy >::value();
  }
  static const char* value(const ::planification::OccupancyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANIFICATION_MESSAGE_OCCUPANCY_H
