// Generated by gencpp from file rrt/Occupancy.msg
// DO NOT EDIT!


#ifndef RRT_MESSAGE_OCCUPANCY_H
#define RRT_MESSAGE_OCCUPANCY_H

#include <ros/service_traits.h>


#include <rrt/OccupancyRequest.h>
#include <rrt/OccupancyResponse.h>


namespace rrt
{

struct Occupancy
{

typedef OccupancyRequest Request;
typedef OccupancyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Occupancy
} // namespace rrt


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rrt::Occupancy > {
  static const char* value()
  {
    return "749473d2fd96a6f0862babbe2b5b4470";
  }

  static const char* value(const ::rrt::Occupancy&) { return value(); }
};

template<>
struct DataType< ::rrt::Occupancy > {
  static const char* value()
  {
    return "rrt/Occupancy";
  }

  static const char* value(const ::rrt::Occupancy&) { return value(); }
};


// service_traits::MD5Sum< ::rrt::OccupancyRequest> should match 
// service_traits::MD5Sum< ::rrt::Occupancy > 
template<>
struct MD5Sum< ::rrt::OccupancyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rrt::Occupancy >::value();
  }
  static const char* value(const ::rrt::OccupancyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt::OccupancyRequest> should match 
// service_traits::DataType< ::rrt::Occupancy > 
template<>
struct DataType< ::rrt::OccupancyRequest>
{
  static const char* value()
  {
    return DataType< ::rrt::Occupancy >::value();
  }
  static const char* value(const ::rrt::OccupancyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rrt::OccupancyResponse> should match 
// service_traits::MD5Sum< ::rrt::Occupancy > 
template<>
struct MD5Sum< ::rrt::OccupancyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rrt::Occupancy >::value();
  }
  static const char* value(const ::rrt::OccupancyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rrt::OccupancyResponse> should match 
// service_traits::DataType< ::rrt::Occupancy > 
template<>
struct DataType< ::rrt::OccupancyResponse>
{
  static const char* value()
  {
    return DataType< ::rrt::Occupancy >::value();
  }
  static const char* value(const ::rrt::OccupancyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RRT_MESSAGE_OCCUPANCY_H
